# Generated by Django 3.1.9 on 2023-09-18 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0012_auto_20230913_1401'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='trips',
            name='purpose',
        ),
        migrations.AlterField(
            model_name='trips',
            name='end_municipality',
            field=models.CharField(choices=[('Tampere', 'Tampere'), ('Kangasala', 'Kangasala'), ('Lempäälä', 'Lempäälä'), ('Nokia', 'Nokia'), ('Orivesi', 'Orivesi'), ('Pirkkala', 'Pirkkala'), ('Vesilahti', 'Vesilahti'), ('Ylöjärvi', 'Ylöjärvi'), ('Muu', 'Muu')], default='Tampere', max_length=20),
        ),
        migrations.AlterField(
            model_name='trips',
            name='purpose',
            field=models.CharField(choices=[('travel_to_work_trip', 'Työmatka'), ('business_trip', 'Työasiamatka'), ('school_trip', 'Koulu- tai opiskelumatka'), ('leisure_trip', 'Vapaa-ajanmatka'), ('shopping_trip', 'Ostosmatka'), ('affair_trip', 'Asiointimatka'), ('passenger_transport_trip', 'Kyyditseminen'), ('tyhja', 'Tyhjä')], default='tyhja', max_length=24),
        ),
        migrations.AlterField(
            model_name='trips',
            name='start_municipality',
            field=models.CharField(choices=[('Tampere', 'Tampere'), ('Kangasala', 'Kangasala'), ('Lempäälä', 'Lempäälä'), ('Nokia', 'Nokia'), ('Orivesi', 'Orivesi'), ('Pirkkala', 'Pirkkala'), ('Vesilahti', 'Vesilahti'), ('Ylöjärvi', 'Ylöjärvi'), ('Muu', 'Muu')], default='Tampere', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='trips',
            constraint=models.CheckConstraint(check=models.Q(purpose__in=['travel_to_work_trip', 'business_trip', 'school_trip', 'leisure_trip', 'shopping_trip', 'affair_trip', 'passenger_transport_trip', 'tyhja']), name='purpose'),
        ),
    ]
