# Generated by Django 3.1.9 on 2023-09-26 19:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0015_auto_20230918_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='legs',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='legs',
            name='received_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='legs',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
