# Generated by Django 3.1.9 on 2023-10-03 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0016_auto_20230926_2216'),
    ]

    operations = [
        migrations.CreateModel(
            name='OriginalTrip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.trips')),
            ],
        ),
    ]
