# Generated by Django 3.1.9 on 2025-08-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0019_partisipants_last_processed_data_received_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='partisipants',
            name='survey_day',
            field=models.DateField(null=True),
        ),
    ]
