# Generated by Django 3.1.9 on 2023-09-21 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0031_device_mocaf_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='mocaf_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='device',
            name='survey_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
