# Generated by Django 3.1.9 on 2024-02-05 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0032_auto_20230921_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='personal_tuning_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
