# Generated by Django 3.1.9 on 2023-09-21 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_auto_20230913_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationtemplate',
            name='action_type',
            field=models.CharField(blank=True, choices=[('open_traffic_survey_correction_info', 'Function check'), ('enable_traffic_survey', 'Survey info message'), ('open_traffic_survey', 'Check your day trips')], max_length=46, null=True),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='event_type',
            field=models.CharField(choices=[('monthly_summary_gold', 'Monthly summary (gold-level budget)'), ('monthly_summary_silver', 'Monthly summary (silver-level budget)'), ('monthly_summary_geq_bronze', 'Monthly summary (bronze-level budget or worse)'), ('monthly_summary_bronze', 'Monthly summary (bronze-level budget)'), ('monthly_summary_no_level', 'Monthly summary (worse than bronze budget)'), ('welcome_message', 'Welcome message'), ('no_recent_trips', 'No recent trips'), ('no_trips-survey', 'No trips after registered to survey'), ('health_summary_gold', 'Health summary (gold-level budget)'), ('health_summary_silver', 'Health summary (silver-level budget)'), ('health_summary_bronze', 'Health summary (bronze-level budget)'), ('health_summary_no_level', 'Health summary (worse than bronze budget)'), ('health_summary_no_data', 'Health summary (no physical activity trips)'), ('timed_message', 'Timed message'), ('end_of_survey', 'Survey has ended'), ('survey_start', 'Survey starting date'), ('reminder-survey', 'Daily trip reminder')], max_length=26),
        ),
    ]
