# Generated by Django 3.1.9 on 2023-09-23 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_auto_20230921_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationtemplate',
            name='action_type',
            field=models.CharField(blank=True, choices=[('open_traffic_survey_correction_info', 'Function check'), ('enable_traffic_survey', 'Survey info message'), ('open_traffic_survey', 'Check your day trips'), ('open_traffic_survey_feedback_link', 'Open link to survey feedback')], max_length=46, null=True),
        ),
    ]
